<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-27 16:00
=======
# Generated by Django 5.1.1 on 2024-10-27 15:50
>>>>>>> b47bcb5a4a957bf187cf67c6bc81198ef39410f2

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=169)),
                ('question', models.TextField()),
                ('answer', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
