# Generated by Django 5.1.2 on 2024-10-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='product_asked',
        ),
    ]
