# Generated by Django 5.1.2 on 2024-10-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0003_question_product_asked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='product_asked',
        ),
    ]
