# Generated by Django 5.1.2 on 2024-10-27 00:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0004_remove_question_product_asked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answered',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
