# Generated by Django 5.1.2 on 2024-10-27 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0006_alter_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
    ]
