# Generated by Django 4.2.16 on 2024-10-26 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myauth', '0002_ajeguser_address_ajeguser_fullname_and_more'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=1)),
                ('total_price', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('payment', models.BooleanField(blank=True, default=False, null=True)),
                ('product', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myauth.ajeguser')),
            ],
        ),
    ]
