# Generated by Django 4.2.16 on 2024-10-27 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_remove_ajeguser_address_remove_ajeguser_email_and_more'),
        ('checkout', '0003_alter_cart_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('cart', models.ManyToManyField(to='checkout.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myauth.ajeguser')),
            ],
        ),
    ]
