# Generated by Django 4.2.16 on 2024-10-15 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_toko', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('harga', models.CharField(max_length=10)),
                ('rating', models.FloatField()),
                ('kategori', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deskripsi', models.TextField()),
                ('toko', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.toko')),
            ],
        ),
    ]
