# Generated by Django 4.2.16 on 2024-10-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgurl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
