# Generated by Django 4.2.16 on 2024-10-15 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toko',
            old_name='harga',
            new_name='range_harga',
        ),
    ]
