# Generated by Django 5.1.4 on 2024-12-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
