# Generated by Django 5.1.4 on 2024-12-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='average_rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
