# Generated by Django 4.2.16 on 2024-10-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_harga_toko_range_harga'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('price_range', models.CharField(max_length=10)),
                ('rating', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='product',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='product',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='product',
            name='toko',
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Deskripsi Kosong'),
        ),
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default='produk', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
    ]
