# Generated by Django 4.2.16 on 2024-10-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_remove_ajeguser__toko_storeuserrelation'),
        ('main', '0003_store_remove_product_deskripsi_remove_product_harga_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Toko',
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.store'),
        ),
    ]
