# Generated by Django 4.2.16 on 2024-10-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_delete_toko_product_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='store',
            name='category',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
