# Generated by Django 4.2.16 on 2024-10-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_store_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='self',
            new_name='category',
        ),
    ]
