<<<<<<< HEAD
# Generated by Django 5.1.2 on 2024-10-27 16:00
=======
# Generated by Django 5.1.1 on 2024-10-27 15:50
>>>>>>> b47bcb5a4a957bf187cf67c6bc81198ef39410f2

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=1000)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myauth.ajeguser')),
                ('target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.comment')),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('star_rating', models.PositiveSmallIntegerField()),
                ('synopsis', models.CharField(blank=True, max_length=50, null=True)),
                ('base_comment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='review.comment')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myauth.ajeguser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
        ),
    ]
