# Generated by Django 5.1.1 on 2024-10-24 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_userreview_base_comment_alter_comment_target_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='review.comment'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='base_comment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='review.comment'),
        ),
    ]
