# Generated by Django 5.1.1 on 2024-10-24 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
        ('review', '0003_alter_comment_target_alter_userreview_base_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myauth.ajeguser'),
        ),
        migrations.AddField(
            model_name='userreview',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myauth.ajeguser'),
        ),
    ]
