# Generated by Django 5.1.1 on 2024-10-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_comment_creator_userreview_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreview',
            name='synopsis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
