# Generated by Django 4.2.16 on 2024-10-16 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjegUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('traveller', 'Traveller'), ('merchant', 'Merchant')], max_length=10)),
                ('ajeg_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ajeg_user', to=settings.AUTH_USER_MODEL)),
                ('store', models.ManyToManyField(blank=True, to='main.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstore', to='main.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstore', to='myauth.ajeguser')),
            ],
        ),
    ]
