# Generated by Django 4.2.16 on 2024-10-12 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ajeguser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='ajeguser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='username',
        ),
        migrations.AddField(
            model_name='ajeguser',
            name='ajeg_user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
    ]
