# Generated by Django 4.2.16 on 2024-10-15 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('myauth', '0002_alter_ajeguser_options_alter_ajeguser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjegMerchant',
            fields=[
                ('ajeguser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myauth.ajeguser')),
                ('toko', models.ManyToManyField(to='main.toko')),
            ],
            bases=('myauth.ajeguser',),
        ),
    ]
