# Generated by Django 4.2.16 on 2024-10-27 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0002_ajeguser_address_ajeguser_fullname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajeguser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
