# Generated by Django 4.2.16 on 2024-10-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0003_ajeguser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajeguser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='ajeguser',
            name='phone_number',
        ),
    ]
