# Generated by Django 4.2.16 on 2024-10-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_harga_toko_range_harga'),
        ('myauth', '0003_ajegmerchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajeguser',
            name='_toko',
            field=models.ManyToManyField(blank=True, to='main.toko'),
        ),
        migrations.DeleteModel(
            name='AjegMerchant',
        ),
    ]
