# Generated by Django 4.2.16 on 2024-10-16 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_store_remove_product_deskripsi_remove_product_harga_and_more'),
        ('myauth', '0005_alter_ajeguser_ajeg_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ajeguser',
            name='_toko',
        ),
        migrations.CreateModel(
            name='StoreUserRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstore', to='main.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userstore', to='myauth.ajeguser')),
            ],
        ),
    ]
